language: c
sudo: false
notifications:
  email:
    - tbekolay@gmail.com

env:
  global:
    - STATIC="false"
    - CONDA_DEPS="jupyter keras matplotlib numpy pytest scipy theano"
    - PIP_DEPS="nengo"

matrix:
  include:
    - env: PYTHON="2.7"
    - env: PYTHON="3.6"
    - env: PYTHON="3.6" STATIC="true"

# Setup Miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python="$PYTHON" pip
  - source activate test

# Install packages with conda, then pip
install:
  - if [[ "$STATIC" == "true" ]]; then
      export CONDA_DEPS="";
      export PIP_DEPS="flake8 pylint";
    fi
  - if [[ -n "$CONDA_DEPS" ]]; then eval conda install --quiet "$CONDA_DEPS"; fi
  - if [[ -n "$PIP_DEPS" ]]; then eval pip install "$PIP_DEPS"; fi
  - export MKL_THREADING_LAYER="GNU"

# Run the tests
script:
  - mkdir -p "$HOME/.ipython/profile_default"
  - "echo 'c.HistoryAccessor.enabled = False\n' > $HOME/.ipython/profile_default/ipython_config.py"
  - if [[ "$STATIC" == "true" ]]; then
      flake8 -v nengo_extras && pylint nengo_extras;
    else
      python setup.py -q develop;
      pytest nengo_extras -v;
    fi
